//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSeguros.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaPolizas
    {
        public int Id { get; set; }
        public string PersonaId { get; set; }
        public int PolizaId { get; set; }
        public int activo { get; set; }
    
        public virtual Polizas Polizas { get; set; }
    }
}
