//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSeguros.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polizas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polizas()
        {
            this.PersonaPolizas = new HashSet<PersonaPolizas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int CodigoCubrimiento { get; set; }
        public System.DateTime InicioVigencia { get; set; }
        public int PeriodoCobertura { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> CodigoRiesgo { get; set; }
        public decimal PorcentajeCobertura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaPolizas> PersonaPolizas { get; set; }
        public virtual CubrimientoPolizas CubrimientoPolizas { get; set; }
        public virtual RiesgosPolizas RiesgosPolizas { get; set; }
    }
}
